language: rust

dist: 
  - bionic

rust:
  - stable

cache:
  - cargo

script:
  # https://tectonic-typesetting.github.io/en-US/install.html
  - sudo apt-get install libfontconfig1-dev libgraphite2-dev libharfbuzz-dev libicu-dev libssl-dev zlib1g-dev
  - cargo install mdbook
  - cargo build
  - cargo test
  - ci/build.sh
