[package]
name = "mdbook-latex"
version = "0.1.0"
authors = ["lbeckman314 <liam@liambeckman.com>"]
edition = "2018"

[dependencies]
mdbook = "0.3.1"
serde = "1.0.98"
serde_derive = "1.0.98"
tectonic = "0.1.11"
md2pdf-mdbook = "*"
